chore(bitrise) current config

diff --git a/bitrise-pfp.yml b/bitrise-pfp.yml
--- a/bitrise-pfp.yml
+++ b/bitrise-pfp.yml
@@ -15,11 +15,13 @@ app:
       is_expand: false
     FASTLANE_LANE: pfp_beta
   - opts:
-      is_expand: true
-    FASTLANE_PASSWORD: Entourage95
-  - CRASHLYTICS_API_TOKEN: 2eca3faf46139913c216b9ee9cf8bee49e70fe20
+      is_expand: false
+    BITRISE_SCHEME: PfpStore
+  - opts:
+      is_expand: false
+    BITRISE_PROJECT_PATH: entourage.xcworkspace
 workflows:
-  beta:
+  beta-backup:
     steps:
     - activate-ssh-key:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
@@ -53,7 +55,14 @@ workflows:
 
             #brew install librsvg
             #brew upgrade imagemagick
-            gem install badge
+            #gem install badge
+
+            curl https://codeload.github.com/ReseauEntourage/badge/tar.gz/master | tar xz
+            pushd badge-master/
+            gem build badge.gemspec
+            gem install badge-0.9.1.gem
+            popd
+            rm -r badge-master/
     - fastlane:
         inputs:
         - lane: "$FASTLANE_LANE"
@@ -61,27 +70,73 @@ workflows:
     - deploy-to-bitrise-io: {}
     - slack:
         inputs:
-        - channel: "#androiddev"
+        - channel: "#iosdev"
         - from_username: Voisin-Age Beta
         - from_username_on_error: Voisin-Age Beta
         - message: |-
             New *PFP dev* iOS build is available: $BITRISE_BUILD_NUMBER  here:
             $BITRISE_APP_URL
         - message_on_error: Oups, build has failed for PFP iOS... @francoispellissier
-            @veronicagliga @Lazar
+            @gregoire
         - pretext: "*Build Succeeded for Voisin-Age Beta!*"
         - pretext_on_error: "*Build Failed for Voisin-Age Beta!*"
         - color: "#00ABF0"
+        - api_token: "$SLACK_BOT_API_TOKEN"
         - webhook_url: https://hooks.slack.com/services/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
     description: Prepares the Voisin-Age Beta builds pinting to preprod/staging environament
-  testflight:
+  beta:
     steps:
     - activate-ssh-key:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
-    - git-clone:
+    - git-clone: {}
+    - ruby-script@2.1.0:
         inputs:
-        - commit: ''
-        - tag: ''
+        - ruby_content: |-
+            PROJECT_KEY = 'EN'
+            RESULT_ENV_VARIABLE = 'JIRA_ISSUE_KEYS'
+
+            puts "Searching issue keys in environment variables"
+
+            ISSUE_KEY_REGEXP = /#{PROJECT_KEY}-\d+/
+            issue_keys = []
+
+            [
+              :BITRISE_GIT_BRANCH,
+              :GIT_CLONE_COMMIT_MESSAGE_SUBJECT,
+              :GIT_CLONE_COMMIT_MESSAGE_BODY
+            ].each do |var|
+              print "#{var}: "
+              value = ENV[var.to_s]
+              if value.nil?
+                puts "(not set)"
+                next
+              end
+              var_issue_keys = value.scan(ISSUE_KEY_REGEXP).uniq
+              puts var_issue_keys.inspect
+              issue_keys += var_issue_keys
+            end
+
+            issue_keys.uniq!
+
+            puts
+
+
+            puts "Issue keys found:"
+            puts issue_keys.inspect
+            puts
+
+            if issue_keys.none?
+              puts "No issue key found, $#{RESULT_ENV_VARIABLE} has not been set."
+            else
+              issue_keys = issue_keys.join('|')
+              puts "Setting $#{RESULT_ENV_VARIABLE} to '#{issue_keys}'."
+              system(
+                'envman', 'add',
+                '--key', RESULT_ENV_VARIABLE.to_s,
+                '--value', issue_keys
+              )
+            end
+        - gemfile_content: ''
     - certificate-and-profile-installer: {}
     - script:
         inputs:
@@ -92,9 +147,156 @@ workflows:
             # debug log
             #set -x
 
+            echo "Download App credentials"
+
+            app_configurations_file=$BITRISE_SOURCE_DIR/AppConfigurations.plist
+
+            # download the fileS
+            wget -O "$app_configurations_file" "$BITRISEIO_APPCONFIGURATIONS_URL"
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            #set -x
+
+            echo "Install dependencies"
+
+            #brew install librsvg
+            #brew upgrade imagemagick
+            #gem install badge
+
+            curl https://codeload.github.com/ReseauEntourage/badge/tar.gz/master | tar xz
+            pushd badge-master/
+            gem build badge.gemspec
+            gem install badge-0.9.1.gem
+            popd
+            rm -r badge-master/
     - fastlane:
         inputs:
-        - lane: deploy_PFP_to_TestFlight
-    - deploy-to-bitrise-io:
+        - lane: "$FASTLANE_LANE"
+        - work_dir: "$FASTLANE_WORK_DIR"
+    - deploy-to-bitrise-io: {}
+    - post-jira-comment-with-build-details@1.1.0:
         inputs:
-        - notify_email_list: gregoire@entourage.social, vaite@entourage.social
+        - base_url: "$JIRA_BASE_URL"
+        - api_token: "$JIRA_API_TOKEN"
+        - user_name: "$JIRA_USER_EMAIL"
+        - issue_keys: "$JIRA_ISSUE_KEYS"
+    - slack:
+        inputs:
+        - channel: "#iosdev"
+        - from_username: Voisin-Age Beta
+        - from_username_on_error: Voisin-Age Beta
+        - message: |-
+            New *PFP dev* iOS build is available: $BITRISE_BUILD_NUMBER  here:
+            $BITRISE_APP_URL
+        - message_on_error: Oups, build has failed for PFP iOS... @francoispellissier
+            @gregoire
+        - pretext: "*Build Succeeded for Voisin-Age Beta!*"
+        - pretext_on_error: "*Build Failed for Voisin-Age Beta!*"
+        - color: "#00ABF0"
+        - api_token: "$SLACK_BOT_API_TOKEN"
+        - fields: |
+            App|${BITRISE_APP_TITLE}
+            Branch|${BITRISE_GIT_BRANCH}
+            Workflow|${BITRISE_TRIGGERED_WORKFLOW_ID}
+            Jira|<${JIRA_BASE_URL}browse/${JIRA_ISSUE_KEYS}|${JIRA_ISSUE_KEYS}>
+        - webhook_url: https://hooks.slack.com/services/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
+    description: Prepares the Voisin-Age Beta builds pinting to preprod/staging environament
+  beta-greg:
+    steps:
+    - cache-pull:
+        title: Fetch cache
+    - script:
+        inputs:
+        - content: |
+            #!/bin/bash
+            set -o errexit
+            set -o pipefail
+
+            echo -e "\n# Downloading code\n"
+            curl -D headers https://codeload.github.com/ReseauEntourage/entourage-ios/tar.gz/$BITRISE_GIT_BRANCH | tar xz --strip-components=1
+
+            GIT_COMMIT=$(cat headers | grep ETag | cut -d\" -f2)
+            envman add --key GIT_COMMIT --value $GIT_COMMIT
+            echo -e "\ngit commit: $GIT_COMMIT\n"
+
+            echo -e "\n# Downloading App credentials\n"
+            curl -Lo AppConfigurations.plist "$BITRISEIO_APPCONFIGURATIONS_URL"
+            echo
+
+            echo -e "\n# Install dependencies\n"
+            #brew install librsvg
+            #brew upgrade imagemagick
+            gem install badge
+            envman add --key GEM_HOME --value "$(gem environment gemdir)"
+            echo
+        title: Download the code and dependencies
+    - cache-push:
+        is_always_run: true
+        inputs:
+        - cache_paths: "$GEM_HOME"
+        title: Cache gems
+    - certificate-and-profile-installer:
+        inputs:
+        - install_defaults: 'no'
+        title: Certificate and profile installation
+    - fastlane:
+        inputs:
+        - update_fastlane: 'false'
+        - lane: build_beta scheme:$BITRISE_SCHEME output_directory:$BITRISE_DEPLOY_DIR
+        title: Build (fastlane)
+    - deploy-to-bitrise-io: {}
+    - slack:
+        run_if: false
+        inputs:
+        - channel: "#androiddev"
+        - from_username: Voisin-Age Beta
+        - from_username_on_error: Voisin-Age Beta
+        - message: |-
+            New *PFP dev* iOS build is available: $BITRISE_BUILD_NUMBER  here:
+            $BITRISE_APP_URL
+        - message_on_error: Oups, build has failed for PFP iOS... @francoispellissier
+            @gregoire
+        - pretext: "*Build Succeeded for Voisin-Age Beta!*"
+        - pretext_on_error: "*Build Failed for Voisin-Age Beta!*"
+        - color: "#00ABF0"
+        - webhook_url: https://hooks.slack.com/services/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
+    description: Prepares the Voisin-Age Beta builds pinting to preprod/staging environament
+  pfp-testflight:
+    steps:
+    - activate-ssh-key:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone: {}
+    - certificate-and-profile-installer: {}
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            #set -x
+            echo "Download App credentials"
+            app_configurations_file=$BITRISE_SOURCE_DIR/AppConfigurations.plist
+            wget -O "$app_configurations_file" "$BITRISEIO_APPCONFIGURATIONS_URL"
+    - xcode-archive:
+        inputs:
+        - export_method: app-store
+    - deploy-to-itunesconnect-application-loader@0.9.4:
+        inputs:
+        - password: "$FASTLANE_PASSWORD"
+        - itunescon_user: "$APPLE_ID"
+    - fabric-crashlytics-beta-deploy@2.2.4:
+        inputs:
+        - build_secret: "$CRASHLYTICS_SECRET"
+        - api_key: "$CRASHLYTICS_API_TOKEN"
+    - deploy-to-bitrise-io:
+        run_if: 
+        inputs:
+        - notify_user_groups: none
+        - notify_email_list: ''
+        is_always_run: false
diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -5,7 +5,7 @@ trigger_map:
 - push_branch: develop
   workflow: Entourage-Beta
 workflows:
-  Entourage-Beta:
+  Entourage-Beta-backup:
     steps:
     - activate-ssh-key:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
@@ -63,11 +63,12 @@ workflows:
             New *Entourage-Beta DEV* iOS build is available: $BITRISE_BUILD_NUMBER  here:
             $BITRISE_APP_URL
         - message_on_error: Oups, build has failed for Entourage iOS... @francoispellissier
-            @veronicagliga @Lazar
+            @gregoire
         - pretext: "*Entourage-Beta Build Succeeded!*"
         - pretext_on_error: "*Build Failed for Entourage Beta!*"
+        - api_token: "$SLACK_BOT_API_TOKEN"
         - webhook_url: https://hooks.slack.com/services/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
-  testflight:
+  FASTLANEtestflight:
     steps:
     - activate-ssh-key:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
@@ -100,7 +101,7 @@ workflows:
     - deploy-to-bitrise-io:
         inputs:
         - notify_email_list: gregoire@entourage.social,  vaite@entourage.social
-  BetaXCODE:
+  Entourage-TestFlight:
     steps:
     - activate-ssh-key:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
@@ -141,15 +142,137 @@ workflows:
         - notify_user_groups: none
     - slack:
         inputs:
-        - channel: "@francoispellissier"
+        - channel: "#iosdev"
+        - from_username: Entourage-Testflight
+        - from_username_on_error: Entourage-Beta
+        - message: 'New *Entourage TestFlight* iOS build is available: $BITRISE_BUILD_NUMBER  '
+        - message_on_error: Oups, build has failed for Entourage iOS... @francoispellissier
+            @gregoire
+        - pretext: "*Entourage TestFlight Build Succeeded!*"
+        - pretext_on_error: "*Build Failed for Entourage TestFlight!*"
+        - buttons: View Build|${BITRISE_BUILD_URL}
+        - webhook_url: https://hooks.slack.com/services/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
+  Entourage-Beta:
+    steps:
+    - activate-ssh-key:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone:
+        inputs:
+        - commit: ''
+        - tag: ''
+    - ruby-script@2.1.0:
+        inputs:
+        - ruby_content: |-
+            PROJECT_KEY = 'EN'
+            RESULT_ENV_VARIABLE = 'JIRA_ISSUE_KEYS'
+
+            puts "Searching issue keys in environment variables"
+
+            ISSUE_KEY_REGEXP = /#{PROJECT_KEY}-\d+/
+            issue_keys = []
+
+            [
+              :BITRISE_GIT_BRANCH,
+              :GIT_CLONE_COMMIT_MESSAGE_SUBJECT,
+              :GIT_CLONE_COMMIT_MESSAGE_BODY
+            ].each do |var|
+              print "#{var}: "
+              value = ENV[var.to_s]
+              if value.nil?
+                puts "(not set)"
+                next
+              end
+              var_issue_keys = value.scan(ISSUE_KEY_REGEXP).uniq
+              puts var_issue_keys.inspect
+              issue_keys += var_issue_keys
+            end
+
+            issue_keys.uniq!
+
+            puts
+
+
+            puts "Issue keys found:"
+            puts issue_keys.inspect
+            puts
+
+            if issue_keys.none?
+              puts "No issue key found, $#{RESULT_ENV_VARIABLE} has not been set."
+            else
+              issue_keys = issue_keys.join('|')
+              puts "Setting $#{RESULT_ENV_VARIABLE} to '#{issue_keys}'."
+              system(
+                'envman', 'add',
+                '--key', RESULT_ENV_VARIABLE.to_s,
+                '--value', issue_keys
+              )
+            end
+        - gemfile_content: ''
+    - certificate-and-profile-installer: {}
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            #set -x
+
+            echo "Download App credentials"
+
+            app_configurations_file=$BITRISE_SOURCE_DIR/AppConfigurations.plist
+
+            # download the fileS
+            wget -O "$app_configurations_file" "$BITRISEIO_APPCONFIGURATIONS_URL"
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            #set -x
+
+            echo "Install dependencies"
+
+            #brew install librsvg
+            #brew upgrade imagemagick
+            #gem install badge
+
+            curl https://codeload.github.com/ReseauEntourage/badge/tar.gz/master | tar xz
+            pushd badge-master/
+            gem build badge.gemspec
+            gem install badge-0.9.1.gem
+            popd
+            rm -r badge-master/
+    - fastlane:
+        inputs:
+        - lane: beta
+    - deploy-to-bitrise-io: {}
+    - post-jira-comment-with-build-details@1.1.0:
+        inputs:
+        - base_url: "$JIRA_BASE_URL"
+        - api_token: "$JIRA_API_TOKEN"
+        - user_name: "$JIRA_USER_EMAIL"
+        - issue_keys: "$JIRA_ISSUE_KEYS"
+    - slack:
+        inputs:
+        - channel: "#iosdev"
         - from_username: Entourage-Beta
         - from_username_on_error: Entourage-Beta
         - message: |-
-            New *Entourage TestFlight* iOS build is available: $BITRISE_BUILD_NUMBER  here:
+            New *Entourage-Beta DEV* iOS build is available: $BITRISE_BUILD_NUMBER  here:
             $BITRISE_APP_URL
         - message_on_error: Oups, build has failed for Entourage iOS... @francoispellissier
-        - pretext: "*Entourage TestFlight Build Succeeded!*"
-        - pretext_on_error: "*Build Failed for Entourage TestFlight!*"
+            @gregoire
+        - pretext: "*Entourage-Beta Build Succeeded!*"
+        - pretext_on_error: "*Build Failed for Entourage Beta!*"
+        - api_token: "$SLACK_BOT_API_TOKEN"
+        - fields: |
+            App|${BITRISE_APP_TITLE}
+            Branch|${BITRISE_GIT_BRANCH}
+            Workflow|${BITRISE_TRIGGERED_WORKFLOW_ID}
+            Jira|<${JIRA_BASE_URL}browse/${JIRA_ISSUE_KEYS}|${JIRA_ISSUE_KEYS}>
         - webhook_url: https://hooks.slack.com/services/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
 app:
   envs:
