chore: fix bitrise workflow to send DSYM and tag with app version/build number

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,6 +1,6 @@
 ---
 format_version: 1.3.0
-default_step_lib_source: 'https://github.com/bitrise-io/bitrise-steplib.git'
+default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 trigger_map:
 - push_branch: develop
   workflow: Entourage-Beta
@@ -22,58 +22,46 @@ workflows:
         - distribution_type: app-store
     - script:
         inputs:
-        - content: >-
+        - content: |-
             #!/bin/bash
-
             # fail if any commands fails
-
             set -e
-
             # debug log
-
             #set -x
-
 
             echo "Download App credentials"
 
-
             app_configurations_file=$BITRISE_SOURCE_DIR/AppConfigurations.plist
 
-
             # download the files
-
-            wget -O "$app_configurations_file"
-            "$BITRISEIO_APPCONFIGURATIONS_URL"
+            wget -O "$app_configurations_file" "$BITRISEIO_APPCONFIGURATIONS_URL"
     - xcode-archive:
         inputs:
         - export_method: app-store
     - deploy-to-bitrise-io:
         inputs:
         - notify_user_groups: none
-        - deploy_path: $BITRISE_IPA_PATH
+        - deploy_path: "$BITRISE_IPA_PATH"
     - deploy-to-itunesconnect-application-loader:
         inputs:
-        - password: $FASTLANE_PASSWORD
-        - itunescon_user: $APPLE_ID
+        - password: "$FASTLANE_PASSWORD"
+        - itunescon_user: "$APPLE_ID"
     - deploy-to-bitrise-io:
         is_always_run: false
         inputs:
         - notify_user_groups: none
     - slack:
         inputs:
-        - channel: '#iosdev'
+        - channel: "#iosdev"
         - from_username: Entourage-Beta
         - from_username_on_error: Entourage-Beta
-        - message: >-
-            New *Entourage-Beta DEV* iOS build is available:
-            $BITRISE_BUILD_NUMBER  here:
-
+        - message: |-
+            New *Entourage-Beta DEV* iOS build is available: $BITRISE_BUILD_NUMBER  here:
             $BITRISE_APP_URL
-        - message_on_error: >-
-            Oups, build has failed for Entourage iOS... @here
-        - pretext: '*Entourage-Beta Build Succeeded!*'
-        - pretext_on_error: '*Build Failed for Entourage Beta!*'
-        - api_token: $SLACK_BOT_API_TOKEN
+        - message_on_error: Oups, build has failed for Entourage iOS... @here
+        - pretext: "*Entourage-Beta Build Succeeded!*"
+        - pretext_on_error: "*Build Failed for Entourage Beta!*"
+        - api_token: "$SLACK_BOT_API_TOKEN"
         - fields: |
             App|${BITRISE_APP_TITLE}
             Branch|${BITRISE_GIT_BRANCH}
@@ -81,15 +69,25 @@ workflows:
             Jira|<${JIRA_BASE_URL}browse/${JIRA_ISSUE_KEYS}|${JIRA_ISSUE_KEYS}>
     - firebase-dsym-upload:
         inputs:
-        - fdu_dsym_location: $BITRISE_DEPLOY_DIR/Entourage-ios.dSYM.zip
-        - fdu_google_services_location: ./entourage/Settings/Environment/GoogleService-Info.plist
+        - fdu_dsym_location: "$BITRISE_DEPLOY_DIR/Entourage-ios.dSYM.zip"
+        - fdu_google_services_location: "./entourage/Settings/Environment/GoogleService-Info.plist"
         is_always_run: true
     - cache-push:
         is_always_run: true
-    - git-tag-project-version-and-build-number:
+    - script:
         inputs:
-        - bitrise_tag_info_plist_path: entourage-Info.plist
-        - bitrise_tag_format: Ent_VERSION
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -ex
+
+            ./Scripts/count_commit.sh
+    - xcode-build-version:
+        inputs:
+        - info_plist_path: "./entourage/entourage-Info.plist"
+    - git-tag:
+        inputs:
+        - tag: Ent_$XBV_PROJECT_VERSION
   Entourage-Beta:
     steps:
     - activate-ssh-key:
@@ -156,63 +154,39 @@ workflows:
         - distribution_type: ad-hoc
     - script:
         inputs:
-        - content: >-
+        - content: |-
             #!/bin/bash
-
             # fail if any commands fails
-
             set -e
-
             # debug log
-
             #set -x
-
 
             echo "Download App credentials"
 
-
             app_configurations_file=$BITRISE_SOURCE_DIR/AppConfigurations.plist
 
-
             # download the fileS
-
-            wget -O "$app_configurations_file"
-            "$BITRISEIO_APPCONFIGURATIONS_URL"
+            wget -O "$app_configurations_file" "$BITRISEIO_APPCONFIGURATIONS_URL"
     - script:
         inputs:
-        - content: >-
+        - content: |-
             #!/bin/bash
-
             # fail if any commands fails
-
             set -e
-
             # debug log
-
             #set -x
-
 
             echo "Install dependencies"
 
-
             #brew install librsvg
-
             #brew upgrade imagemagick
-
             #gem install badge
 
-
-            curl https://codeload.github.com/ReseauEntourage/badge/tar.gz/master
-            | tar xz
-
+            curl https://codeload.github.com/ReseauEntourage/badge/tar.gz/master | tar xz
             pushd badge-master/
-
             gem build badge.gemspec
-
             gem install badge-0.9.1.gem
-
             popd
-
             rm -r badge-master/
     - fastlane:
         inputs:
@@ -220,25 +194,22 @@ workflows:
     - deploy-to-bitrise-io: {}
     - post-jira-comment-with-build-details:
         inputs:
-        - base_url: $JIRA_BASE_URL
-        - api_token: $JIRA_API_TOKEN
-        - user_name: $JIRA_USER_EMAIL
-        - issue_keys: $JIRA_ISSUE_KEYS
+        - base_url: "$JIRA_BASE_URL"
+        - api_token: "$JIRA_API_TOKEN"
+        - user_name: "$JIRA_USER_EMAIL"
+        - issue_keys: "$JIRA_ISSUE_KEYS"
     - slack:
         inputs:
-        - channel: '#iosdev'
+        - channel: "#iosdev"
         - from_username: Entourage-Beta
         - from_username_on_error: Entourage-Beta
-        - message: >-
-            New *Entourage-Beta DEV* iOS build is available:
-            $BITRISE_BUILD_NUMBER  here:
-
+        - message: |-
+            New *Entourage-Beta DEV* iOS build is available: $BITRISE_BUILD_NUMBER  here:
             $BITRISE_APP_URL
-        - message_on_error: >-
-            Oups, build has failed for Entourage iOS... @here
-        - pretext: '*Entourage-Beta Build Succeeded!*'
-        - pretext_on_error: '*Build Failed for Entourage Beta!*'
-        - api_token: $SLACK_BOT_API_TOKEN
+        - message_on_error: Oups, build has failed for Entourage iOS... @here
+        - pretext: "*Entourage-Beta Build Succeeded!*"
+        - pretext_on_error: "*Build Failed for Entourage Beta!*"
+        - api_token: "$SLACK_BOT_API_TOKEN"
         - fields: |
             App|${BITRISE_APP_TITLE}
             Branch|${BITRISE_GIT_BRANCH}
@@ -246,8 +217,7 @@ workflows:
             Jira|<${JIRA_BASE_URL}browse/${JIRA_ISSUE_KEYS}|${JIRA_ISSUE_KEYS}>
     - firebase-dsym-upload@2:
         inputs:
-        - fdu_google_services_location: >-
-            ./entourage/Settings/Environment/GoogleService-Info-social.entourage.ios.beta.plist
+        - fdu_google_services_location: "./entourage/Settings/Environment/GoogleService-Info-social.entourage.ios.beta.plist"
     - cache-push: {}
   Entourage-NoFastlane:
     steps:
@@ -314,21 +284,14 @@ workflows:
         - distribution_type: ad-hoc
     - script:
         inputs:
-        - content: >-
+        - content: |-
             #!/bin/bash
-
             # fail if any commands fails
-
             set -e
-
             echo "Download App credentials"
- 
             app_configurations_file=$BITRISE_SOURCE_DIR/AppConfigurations.plist
- 
             # download the fileS
- 
-            wget -O "$app_configurations_file"
-            "$BITRISEIO_APPCONFIGURATIONS_URL"
+            wget -O "$app_configurations_file" "$BITRISEIO_APPCONFIGURATIONS_URL"
     - xcode-archive:
         inputs:
         - export_method: ad-hoc
@@ -341,50 +304,8 @@ workflows:
     steps:
     - trigger-bitrise-workflow:
         inputs:
-        - api_token: $BUILD_TRIGGER
+        - api_token: "$BUILD_TRIGGER"
         - workflow_id: Entourage-Beta
-  TestGitTag:
-    steps:
-    - activate-ssh-key:
-        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
-    - git-clone:
-        inputs:
-        - commit: ''
-        - tag: ''
-    - cocoapods-install:
-        inputs:
-        - verbose: 'false'
-    - ios-auto-provision-appstoreconnect:
-        inputs:
-        - distribution_type: app-store
-    - script:
-        inputs:
-        - content: >-
-            #!/bin/bash
-
-            # fail if any commands fails
-
-            set -e
-
-            # debug log
-
-            #set -x
-
-
-            echo "Download App credentials"
-
-
-            app_configurations_file=$BITRISE_SOURCE_DIR/AppConfigurations.plist
-
-
-            # download the files
-
-            wget -O "$app_configurations_file"
-            "$BITRISEIO_APPCONFIGURATIONS_URL"
-    - git-tag-project-version-and-build-number:
-        inputs:
-        - bitrise_tag_info_plist_path: entourage-Info.plist
-        - bitrise_tag_format: Ent_$_VERSION_
 app:
   envs:
   - opts:
