chore(bitrise) change bitrise config

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -2,16 +2,66 @@
 format_version: 1.2.0
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 trigger_map:
-- push_branch: v2.2
+- push_branch: develop
   workflow: beta
-- pull_request_source_branch: "*"
-  workflow: beta
+- tag: "*"
+  workflow: testflight
 workflows:
   beta:
     steps:
+    - activate-ssh-key:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone:
+        inputs:
+        - commit: ''
+        - tag: ''
+    - certificate-and-profile-installer: {}
+    - script:
+        inputs:
+        - content: |
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            #set -x
+
+            echo "Download Amazon credentials"
+
+            staging_file_local_path=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/staging.plist
+            prod_file_local_path=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/prod.plist
+            amazon_consts_file=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/OTAmazonConsts.h
+            mixpanel_consts_file=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/OTMixpanelConsts.h
+
+            # download the fileS
+            wget -O "$staging_file_local_path" "$BITRISEIO_STAGING_PLIST_URL"
+            wget -O "$prod_file_local_path" "$BITRISEIO_PRODUCTION_PLIST_URL"
+
+            wget -O "$amazon_consts_file" "$BITRISEIO_OTAMAZONCONSTS_URL"
+            wget -O "$mixpanel_consts_file" "$BITRISEIO_OTMIXPANELCONSTSDBG_URL"
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            #set -x
+
+            echo "Install dependencies"
+
+            brew install librsvg
+            #brew upgrade imagemagick
+            gem install badge
+    - fastlane:
+        inputs:
+        - lane: beta appaloosa_api_key:$APPALOOSA_API_KEY appaloosa_store_id:$APPALOOSA_STORE_ID
+    - deploy-to-bitrise-io:
+        is_always_run: false
+  beta2.1:
+    steps:
     - activate-ssh-key@3.1.1:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
-    - git-clone@3.4.0: {}
+    - git-clone: {}
     - certificate-and-profile-installer@1.8.1: {}
     - script@1.1.3:
         inputs:
@@ -26,16 +76,178 @@ workflows:
 
             staging_file_local_path=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/staging.plist
             prod_file_local_path=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/prod.plist
+            amazon_consts_file=$BITRISE_SOURCE_DIR/entourage/Classes/OTAmazonConsts.h
 
             # download the file
-            #wget -O "$staging_file_local_path" "$BITRISEIO_STAGING_PLIST_URL"
-            #wget -O "$prod_file_local_path" "$BITRISEIO_PROD_PLIST_URL"
+
+            wget -O "$amazon_consts_file" "$BITRISEIO_OTAMAZONCONSTS_URL"
 
             gem install badge
-    - fastlane@2.2.0:
+    - set-ios-version@1.1.1:
         inputs:
-        - lane: beta appaloosa_api_key:$APPALOOSA_API_KEY appaloosa_store_id:$APPALOOSA_STORE_ID
+        - info_plist_file: "$BITRISE_SOURCE_DIR/entourage/entourage-Info.plist"
+        - bundle_version: 2.1.2.$BITRISE_BUILD_NUMBER
+        - bundle_version_short: 2.1.2.$BITRISE_BUILD_NUMBER
+        - version_short_offset: ''
+    - xcode-archive@2.0.0:
+        inputs:
+        - team_id: ''
+        - configuration: ''
+        - force_team_id: ''
+        - force_code_sign_identity: ''
+        - force_provisioning_profile_specifier: ''
+        - force_provisioning_profile: ''
+        - custom_export_options_plist_content: ''
+    - appaloosa@1.3.0:
+        inputs:
+        - user_email: ''
+        - appaloosa_api_key: fhyk78ldv01r2yazk1h91949wvhopo
+        - store_id: '3949'
+        - screenshot1: ''
+        - screenshot2: ''
+        - screenshot3: ''
+        - screenshot4: ''
+        - screenshot5: ''
+        - description: ''
+        - changelog: ''
+        - group_ids: '3446'
     - deploy-to-bitrise-io@1.2.5: {}
+  testflight:
+    steps:
+    - activate-ssh-key:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone:
+        inputs:
+        - commit: ''
+        - tag: ''
+    - cache-pull: {}
+    - certificate-and-profile-installer: {}
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            echo "Download Amazon credentials"
+
+            staging_file_local_path=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/staging.plist
+            prod_file_local_path=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/prod.plist
+            amazon_consts_file=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/OTAmazonConsts.h
+            mixpanel_consts_file=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/OTMixpanelConsts.h
+
+            # download the fileS
+            wget -O "$staging_file_local_path" "$BITRISEIO_STAGING_PLIST_URL"
+            wget -O "$prod_file_local_path" "$BITRISEIO_PRODUCTION_PLIST_URL"
+
+            wget -O "$amazon_consts_file" "$BITRISEIO_OTAMAZONCONSTS_URL"
+            wget -O "$mixpanel_consts_file" "$BITRISEIO_OTMIXPANELCONSTS_URL"
+
+            #gem install badge
+    - recursive-touch:
+        inputs:
+        - touch_time: '2017-10-25T15:00:00+00:00'
+    - fastlane:
+        inputs:
+        - lane: deploy_to_TestFlight
+    - fastlane:
+        inputs:
+        - lane: refresh_dsyms api_token:$CRASHLYTICS_API_TOKEN
+        - update_fastlane: 'false'
+    - deploy-to-bitrise-io: {}
+    - cache-push:
+        inputs:
+        - cache_paths: "~/Library/Developer/Xcode/DerivedData"
+        - ignore_check_on_paths: "~/Library/Developer/Xcode/DerivedData"
+  testflightLIGHT:
+    steps:
+    - activate-ssh-key:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone:
+        inputs:
+        - commit: ''
+        - tag: ''
+    - cache-pull@2.0.0: {}
+    - certificate-and-profile-installer: {}
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            #set -x
+
+            echo "Download Amazon credentials"
+
+            staging_file_local_path=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/staging.plist
+            prod_file_local_path=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/prod.plist
+            amazon_consts_file=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/OTAmazonConsts.h
+            mixpanel_consts_file=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/OTMixpanelConsts.h
+
+            # download the fileS
+            wget -O "$staging_file_local_path" "$BITRISEIO_STAGING_PLIST_URL"
+            wget -O "$prod_file_local_path" "$BITRISEIO_PRODUCTION_PLIST_URL"
+
+            wget -O "$amazon_consts_file" "$BITRISEIO_OTAMAZONCONSTS_URL"
+            wget -O "$mixpanel_consts_file" "$BITRISEIO_OTMIXPANELCONSTS_URL"
+
+            #gem install badge
+    - recursive-touch@0.9.0: {}
+    - fastlane:
+        inputs:
+        - lane: deploy_to_TestFlight
+    - deploy-to-bitrise-io:
+        inputs:
+        - notify_email_list: antoine@entourage.social, gregoire@entourage.social,
+            vaite@entourage.social
+    - cache-push@2.0.2:
+        inputs:
+        - cache_paths: "~/Library/Developer/Xcode/DerivedData"
+        - ignore_check_on_paths: "~/Library/Developer/Xcode/DerivedData"
+  newtestflightDEV:
+    steps:
+    - activate-ssh-key: {}
+    - git-clone: {}
+    - cache-pull: {}
+    - certificate-and-profile-installer: {}
+    - script:
+        inputs:
+        - content: |
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            echo "Download Amazon credentials"
+
+            staging_file_local_path=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/staging.plist
+            prod_file_local_path=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/prod.plist
+            amazon_consts_file=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/OTAmazonConsts.h
+            mixpanel_consts_file=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/OTMixpanelConsts.h
+
+            # download the files
+            wget -O "$staging_file_local_path" "$BITRISEIO_STAGING_PLIST_URL"
+            wget -O "$prod_file_local_path" "$BITRISEIO_PRODUCTION_PLIST_URL"
+
+            wget -O "$amazon_consts_file" "$BITRISEIO_OTAMAZONCONSTS_URL"
+            wget -O "$mixpanel_consts_file" "$BITRISEIO_OTMIXPANELCONSTS_URL"
+    - recreate-user-schemes:
+        inputs:
+        - project_path: "$BITRISE_PROJECT_PATH"
+    - cocoapods-install: {}
+    - recursive-touch: {}
+    - xcode-archive:
+        inputs:
+        - export_method: app-store
+    - deploy-to-itunesconnect-deliver: {}
+    - deploy-to-bitrise-io:
+        inputs:
+        - notify_user_groups: owner
+    - cache-push: {}
 app:
   envs:
   - opts:
@@ -43,7 +255,7 @@ app:
     BITRISE_PROJECT_PATH: entourage.xcworkspace
   - opts:
       is_expand: false
-    BITRISE_SCHEME: entourage
+    BITRISE_SCHEME: Entourage-ios
   - opts:
       is_expand: true
     APPALOOSA_STORE_ID: '3949'
@@ -53,3 +265,4 @@ app:
   - opts:
       is_expand: true
     FASTLANE_PASSWORD: Entourage95
+  - CRASHLYTICS_API_TOKEN: 2eca3faf46139913c216b9ee9cf8bee49e70fe20
