chore: add workflow for pushing DSYM to Firebase

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -5,6 +5,58 @@ trigger_map:
 - push_branch: develop
   workflow: Entourage-Preprod
 workflows:
+  Entourage-UploadFirebaseDSYM:
+    steps:
+    - activate-ssh-key:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone: {}
+    - cache-pull: {}
+    - cocoapods-install: {}
+    - ios-auto-provision-appstoreconnect:
+        inputs:
+        - distribution_type: app-store
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            #set -x
+
+            echo "Download App credentials"
+
+            app_configurations_file=$BITRISE_SOURCE_DIR/AppConfigurations.plist
+
+            # download the files
+            wget -O "$app_configurations_file" "$BITRISEIO_APPCONFIGURATIONS_URL"
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -ex
+
+            ./Scripts/count_commit.sh
+    - xcode-archive:
+        inputs:
+        - distribution_method: app-store
+    - deploy-to-bitrise-io:
+        inputs:
+        - notify_user_groups: none
+        - deploy_path: "$BITRISE_IPA_PATH"
+    - deploy-to-bitrise-io:
+        is_always_run: false
+        inputs:
+        - notify_user_groups: none
+    - firebase-dsym-upload:
+        inputs:
+        - fdu_dsym_location: "$BITRISE_DEPLOY_DIR/Entourage.dSYM.zip"
+        - fdu_google_services_location: "./entourage/Settings/Environment/GoogleService-Info.plist"
+        is_always_run: true
+    - xcode-build-version:
+        inputs:
+        - info_plist_path: "./entourage/entourage-Info.plist"
   Entourage-TestFlight:
     steps:
     - activate-ssh-key:
