chore: trying to fix bitrise config

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,22 +1,31 @@
----
 format_version: 1.3.0
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
+project_type: ""
+app:
+  envs:
+  - BITRISE_PROJECT_PATH: entourage.xcworkspace
+    opts:
+      is_expand: false
+  - BITRISE_SCHEME: Entourage-ios
+    opts:
+      is_expand: false
 trigger_map:
 - push_branch: develop
   workflow: Entourage-Preprod
 workflows:
   Entourage-Preprod:
+    before_run:
+    - Prepare
+    envs:
+    - BITRISE_SCHEME: EntourageBeta
+      opts:
+        is_expand: false
     steps:
-    - activate-ssh-key:
-        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
-    - git-clone:
+    - xcode-archive:
         inputs:
-        - commit: ''
-        - tag: ''
-    - cache-pull: {}
-    - cocoapods-install:
-        inputs:
-        - verbose: 'false'
+        - register_test_devices: "yes"
+        - distribution_method: ad-hoc
+    - deploy-to-bitrise-io: {}
     - ruby-script:
         inputs:
         - ruby_content: |-
@@ -63,94 +72,35 @@ workflows:
                 '--value', issue_keys
                 )
             end
-        - gemfile_content: ''
-    - script:
-        inputs:
-        - content: |-
-            #!/bin/bash
-            # fail if any commands fails
-            set -e
-            echo "Download App credentials"
-            app_configurations_file=$BITRISE_SOURCE_DIR/AppConfigurations.plist
-            # download the fileS
-            wget -O "$app_configurations_file" "$BITRISEIO_APPCONFIGURATIONS_URL"
-    - script:
-        inputs:
-        - content: |-
-            #!/usr/bin/env bash
-            # fail if any commands fails
-            set -ex
-
-            ./Scripts/count_commit.sh
-    - xcode-archive:
-        inputs:
-        - automatic_code_signing: api-key
-        - register_test_devices: 'yes'
-        - distribution_method: ad-hoc
-    - deploy-to-bitrise-io: {}
+        - gemfile_content: ""
     - post-jira-comment-with-build-details:
         inputs:
-        - base_url: "$JIRA_BASE_URL"
-        - api_token: "$JIRA_API_TOKEN"
-        - user_name: "$JIRA_USER_EMAIL"
-        - issue_keys: "$JIRA_ISSUE_KEYS"
+        - base_url: $JIRA_BASE_URL
+        - api_token: $JIRA_API_TOKEN
+        - user_name: $JIRA_USER_EMAIL
+        - issue_keys: $JIRA_ISSUE_KEYS
     - slack:
         inputs:
-        - channel: "#iosdev"
+        - channel: '#iosdev'
         - from_username: Entourage-Beta
         - from_username_on_error: Entourage-Beta
         - message: |-
             New *Entourage-Beta DEV* iOS build is available: $BITRISE_BUILD_NUMBER  here:
             $BITRISE_APP_URL
         - message_on_error: Oups, build has failed for Entourage iOS... @here
-        - pretext: "*Entourage-Beta Build Succeeded!*"
-        - pretext_on_error: "*Build Failed for Entourage Beta!*"
-        - api_token: "$SLACK_BOT_API_TOKEN"
+        - pretext: '*Entourage-Beta Build Succeeded!*'
+        - pretext_on_error: '*Build Failed for Entourage Beta!*'
+        - api_token: $SLACK_BOT_API_TOKEN
         - fields: |
             App|${BITRISE_APP_TITLE}
             Branch|${BITRISE_GIT_BRANCH}
             Workflow|${BITRISE_TRIGGERED_WORKFLOW_ID}
             Jira|<${JIRA_BASE_URL}browse/${JIRA_ISSUE_KEYS}|${JIRA_ISSUE_KEYS}>
-    - cache-push:
-        is_always_run: true
-    - firebase-dsym-upload:
-        inputs:
-        - fdu_logging: 'yes'
-        - fdu_google_services_location: "./entourage/Settings/Environment/GoogleService-Info-social.entourage.ios.beta.plist"
-    envs:
-    - opts:
-        is_expand: false
-      BITRISE_SCHEME: EntourageBeta
+    - cache-push: {}
   Entourage-TestFlight:
+    before_run:
+    - Prepare
     steps:
-    - activate-ssh-key:
-        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
-    - git-clone: {}
-    - cache-pull: {}
-    - cocoapods-install: {}
-    - script:
-        inputs:
-        - content: |-
-            #!/bin/bash
-            # fail if any commands fails
-            set -e
-            # debug log
-            #set -x
-
-            echo "Download App credentials"
-
-            app_configurations_file=$BITRISE_SOURCE_DIR/AppConfigurations.plist
-
-            # download the files
-            wget -O "$app_configurations_file" "$BITRISEIO_APPCONFIGURATIONS_URL"
-    - script:
-        inputs:
-        - content: |-
-            #!/usr/bin/env bash
-            # fail if any commands fails
-            set -ex
-
-            ./Scripts/count_commit.sh
     - xcode-archive:
         inputs:
         - automatic_code_signing: api-key
@@ -158,48 +108,60 @@ workflows:
     - deploy-to-bitrise-io:
         inputs:
         - notify_user_groups: none
-        - deploy_path: "$BITRISE_IPA_PATH"
+        - deploy_path: $BITRISE_IPA_PATH
     - deploy-to-itunesconnect-application-loader:
         inputs:
-        - password: "$FASTLANE_PASSWORD"
-        - itunescon_user: "$APPLE_ID"
+        - password: $FASTLANE_PASSWORD
+        - itunescon_user: $APPLE_ID
     - deploy-to-bitrise-io:
         is_always_run: false
         inputs:
         - notify_user_groups: none
+    - cache-push: {}
+    - xcode-build-version:
+        inputs:
+        - info_plist_path: ./entourage/entourage-Info.plist
+    - git-tag:
+        inputs:
+        - tag: Ent_TestFlight_$XBV_PROJECT_VERSION
     - slack:
         inputs:
-        - channel: "#iosdev"
+        - channel: '#iosdev'
         - from_username: Entourage-Beta
         - from_username_on_error: Entourage-Beta
         - message: |-
             New *Entourage-Beta DEV* iOS build is available: $BITRISE_BUILD_NUMBER  here:
             $BITRISE_APP_URL
         - message_on_error: Oups, build has failed for Entourage iOS... @here
-        - pretext: "*Entourage-Beta Build Succeeded!*"
-        - pretext_on_error: "*Build Failed for Entourage Beta!*"
-        - api_token: "$SLACK_BOT_API_TOKEN"
+        - pretext: '*Entourage-Beta Build Succeeded!*'
+        - pretext_on_error: '*Build Failed for Entourage Beta!*'
+        - api_token: $SLACK_BOT_API_TOKEN
         - fields: |
             App|${BITRISE_APP_TITLE}
             Branch|${BITRISE_GIT_BRANCH}
             Workflow|${BITRISE_TRIGGERED_WORKFLOW_ID}
-            Jira|<${JIRA_BASE_URL}browse/${JIRA_ISSUE_KEYS}|${JIRA_ISSUE_KEYS}>
-    - cache-push: {}
-    - xcode-build-version:
+  Prepare:
+    steps:
+    - activate-ssh-key:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone:
         inputs:
-        - info_plist_path: "./entourage/entourage-Info.plist"
-    - git-tag:
+        - commit: ""
+        - tag: ""
+    - cache-pull: {}
+    - cocoapods-install:
         inputs:
-        - tag: Ent_TestFlight_$XBV_PROJECT_VERSION
-    - firebase-dsym-upload:
+        - verbose: "false"
+    - file-downloader@1:
         inputs:
-        - fdu_dsym_location: "$BITRISE_DEPLOY_DIR/Entourage.dSYM.zip"
-        - fdu_google_services_location: "./entourage/Settings/Environment/GoogleService-Info.plist"
-app:
-  envs:
-  - opts:
-      is_expand: false
-    BITRISE_PROJECT_PATH: entourage.xcworkspace
-  - opts:
-      is_expand: false
-    BITRISE_SCHEME: Entourage-ios
+        - destination: $BITRISEIO_APPCONFIGURATIONS_URL
+        - file_permission: "600"
+        - source: $BITRISE_SOURCE_DIR/AppConfigurations.plist
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -ex
+
+            ./Scripts/count_commit.sh
