chore(fastlane) removing appaloosa from bitrise build

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -2,18 +2,21 @@
 format_version: 1.2.0
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 trigger_map:
-- push_branch: v2.2
-  workflow: beta
-- pull_request_source_branch: "*"
-  workflow: beta
+- push_branch: develop
+  workflow: Entourage-Beta
+- push_branch: whitelabeling
+  workflow: Voisin-Age-Beta
 workflows:
-  beta:
+  testflightFull:
     steps:
-    - activate-ssh-key@3.1.1:
+    - activate-ssh-key:
         run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
-    - git-clone@3.4.0: {}
-    - certificate-and-profile-installer@1.8.1: {}
-    - script@1.1.3:
+    - git-clone:
+        inputs:
+        - commit: ''
+        - tag: ''
+    - certificate-and-profile-installer: {}
+    - script:
         inputs:
         - content: |-
             #!/bin/bash
@@ -24,18 +27,170 @@ workflows:
 
             echo "Download Amazon credentials"
 
-            staging_file_local_path=$BITRISE_SOURCE_DIR/staging.plist
-            prod_file_local_path=$BITRISE_SOURCE_DIR/prod.plist
+            amazon_consts_file=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/OTAmazonConsts.h
+            mixpanel_consts_file=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/OTMixpanelConsts.h
 
-            # download the file
-            #wget -O "$staging_file_local_path" "$BITRISEIO_STAGING_PLIST_URL"
-            #wget -O "$prod_file_local_path" "$BITRISEIO_PROD_PLIST_URL"
+            # download the fileS
+            wget -O "$amazon_consts_file" "$BITRISEIO_OTAMAZONCONSTS_URL"
+            wget -O "$mixpanel_consts_file" "$BITRISEIO_OTMIXPANELCONSTS_URL"
 
+            #gem install badge
+    - fastlane:
+        inputs:
+        - lane: deploy_to_TestFlight
+    - fastlane:
+        inputs:
+        - lane: refresh_dsyms api_token:$CRASHLYTICS_API_TOKEN
+    - deploy-to-bitrise-io:
+        inputs:
+        - notify_email_list: antoine@entourage.social, gregoire@entourage.social,  vaite@entourage.social
+  testflightNocache:
+    steps:
+    - activate-ssh-key:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone:
+        inputs:
+        - commit: ''
+        - tag: ''
+    - certificate-and-profile-installer: {}
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            #set -x
+
+            echo "Download Amazon credentials"
+
+            amazon_consts_file=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/OTAmazonConsts.h
+            mixpanel_consts_file=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/OTMixpanelConsts.h
+
+            # download the fileS
+            wget -O "$amazon_consts_file" "$BITRISEIO_OTAMAZONCONSTS_URL"
+            wget -O "$mixpanel_consts_file" "$BITRISEIO_OTMIXPANELCONSTS_URL"
+
+            #gem install badge
+    - fastlane:
+        inputs:
+        - lane: deploy_to_TestFlight
+    - deploy-to-bitrise-io:
+        inputs:
+        - notify_email_list: antoine@entourage.social, gregoire@entourage.social,
+            vaite@entourage.social
+  Voisin-Age-Beta:
+    steps:
+    - activate-ssh-key:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone:
+        inputs:
+        - commit: ''
+        - tag: ''
+    - certificate-and-profile-installer: {}
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            #set -x
+
+            echo "Download App credentials"
+
+            app_configurations_file=$BITRISE_SOURCE_DIR/AppConfigurations.plist
+
+            # download the fileS
+            wget -O "$app_configurations_file" "$BITRISEIO_APPCONFIGURATIONS_URL"
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            #set -x
+
+            echo "Install dependencies"
+
+            #brew install librsvg
+            #brew upgrade imagemagick
             gem install badge
-    - fastlane@2.2.0:
+    - fastlane:
+        inputs:
+        - lane: pfp_beta appaloosa_api_key:$APPALOOSA_API_KEY appaloosa_store_id:$APPALOOSA_STORE_ID
+    - deploy-to-bitrise-io: {}
+    - slack:
+        inputs:
+        - channel: "#androiddev"
+        - from_username: Voisin-Age Beta
+        - from_username_on_error: Voisin-Age Beta
+        - message: |-
+            New *PFP dev* iOS build is available: $BITRISE_BUILD_NUMBER  here:
+            $BITRISE_APP_URL
+        - message_on_error: Oups, build has failed for PFP iOS... @francoispellissier
+            @veronicagliga @Lazar
+        - pretext: "*Build Succeeded for Voisin-Age Beta!*"
+        - pretext_on_error: "*Build Failed for Voisin-Age Beta!*"
+        - color: "#00ABF0"
+        - webhook_url: https://hooks.slack.com/services/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
+    description: Prepares the Voisin-Age Beta builds pinting to preprod/staging environament
+  Entourage-Beta:
+    steps:
+    - activate-ssh-key:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone:
+        inputs:
+        - commit: ''
+        - tag: ''
+    - certificate-and-profile-installer: {}
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            #set -x
+
+            echo "Download App credentials"
+
+            app_configurations_file=$BITRISE_SOURCE_DIR/AppConfigurations.plist
+
+            # download the fileS
+            wget -O "$app_configurations_file" "$BITRISEIO_APPCONFIGURATIONS_URL"
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            #set -x
+
+            echo "Install dependencies"
+
+            #brew install librsvg
+            #brew upgrade imagemagick
+            gem install badge
+    - fastlane:
         inputs:
         - lane: beta appaloosa_api_key:$APPALOOSA_API_KEY appaloosa_store_id:$APPALOOSA_STORE_ID
-    - deploy-to-bitrise-io@1.2.5: {}
+    - deploy-to-bitrise-io: {}
+    - slack:
+        inputs:
+        - channel: "#androiddev"
+        - from_username: Entourage-Beta
+        - from_username_on_error: Entourage-Beta
+        - message: |-
+            New *Entourage-Beta DEV* iOS build is available: $BITRISE_BUILD_NUMBER  here:
+            $BITRISE_APP_URL
+        - message_on_error: Oups, build has failed for Entourage iOS... @francoispellissier
+            @veronicagliga @Lazar
+        - pretext: "*Entourage-Beta Build Succeeded!*"
+        - pretext_on_error: "*Build Failed for Entourage Beta!*"
+        - webhook_url: https://hooks.slack.com/services/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
 app:
   envs:
   - opts:
@@ -43,7 +198,7 @@ app:
     BITRISE_PROJECT_PATH: entourage.xcworkspace
   - opts:
       is_expand: false
-    BITRISE_SCHEME: entourage
+    BITRISE_SCHEME: Entourage-ios
   - opts:
       is_expand: true
     APPALOOSA_STORE_ID: '3949'
@@ -53,3 +208,4 @@ app:
   - opts:
       is_expand: true
     FASTLANE_PASSWORD: Entourage95
+  - CRASHLYTICS_API_TOKEN: 2eca3faf46139913c216b9ee9cf8bee49e70fe20
