chore(bitrise) remove use of bitrise PLIST files, using git ones

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -4,8 +4,6 @@ default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 trigger_map:
 - push_branch: develop
   workflow: beta
-- tag: "*"
-  workflow: testflightFull
 workflows:
   beta:
     steps:
@@ -27,14 +25,14 @@ workflows:
 
             echo "Download Amazon credentials"
 
-            staging_file_local_path=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/staging.plist
-            prod_file_local_path=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/prod.plist
+            #staging_file_local_path=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/staging.plist
+            #prod_file_local_path=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/prod.plist
             amazon_consts_file=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/OTAmazonConsts.h
             mixpanel_consts_file=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/OTMixpanelConsts.h
 
             # download the fileS
-            wget -O "$staging_file_local_path" "$BITRISEIO_STAGING_PLIST_URL"
-            wget -O "$prod_file_local_path" "$BITRISEIO_PRODUCTION_PLIST_URL"
+            #wget -O "$staging_file_local_path" "$BITRISEIO_STAGING_PLIST_URL"
+            #wget -O "$prod_file_local_path" "$BITRISEIO_PRODUCTION_PLIST_URL"
 
             wget -O "$amazon_consts_file" "$BITRISEIO_OTAMAZONCONSTS_URL"
             wget -O "$mixpanel_consts_file" "$BITRISEIO_OTMIXPANELCONSTSDBG_URL"
@@ -49,23 +47,22 @@ workflows:
 
             echo "Install dependencies"
 
-            brew install librsvg
+            #brew install librsvg
             #brew upgrade imagemagick
             gem install badge
     - fastlane:
         inputs:
         - lane: beta appaloosa_api_key:$APPALOOSA_API_KEY appaloosa_store_id:$APPALOOSA_STORE_ID
-    - deploy-to-bitrise-io:
-        is_always_run: false
+    - deploy-to-bitrise-io: {}
     - slack:
         inputs:
         - channel: "#androiddev"
         - from_username: 'Bitrise '
         - from_username_on_error: Bitrise
         - message: |-
-            New *DEV* android build is available: $BITRISE_BUILD_NUMBER  here:
+            New *DEV* iOS build is available: $BITRISE_BUILD_NUMBER  here:
             $BITRISE_APP_URL
-        - message_on_error: Oups, build has failed for iOS...
+        - message_on_error: Oups, build has failed for iOS... @francois @veronicagliga
         - webhook_url: https://hooks.slack.com/services/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
   testflightFull:
     steps:
@@ -157,14 +154,14 @@ workflows:
     - fastlane:
         inputs:
         - lane: deploy_to_TestFlight
-    - deploy-to-bitrise-io:
-        inputs:
-        - notify_email_list: antoine@entourage.social, gregoire@entourage.social,
-            vaite@entourage.social
     - cache-push:
         inputs:
         - cache_paths: "~/Library/Developer/Xcode/DerivedData"
         - ignore_check_on_paths: "~/Library/Developer/Xcode/DerivedData"
+    - deploy-to-bitrise-io:
+        inputs:
+        - notify_email_list: antoine@entourage.social, gregoire@entourage.social,
+            vaite@entourage.social
   WIPnewtfDEV:
     steps:
     - activate-ssh-key: {}
@@ -261,6 +258,46 @@ workflows:
         - changelog: ''
         - group_ids: '3446'
     - deploy-to-bitrise-io@1.2.5: {}
+  testCrashlytics:
+    steps:
+    - activate-ssh-key:
+        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
+    - git-clone:
+        inputs:
+        - commit: ''
+        - tag: ''
+    - cache-pull: {}
+    - certificate-and-profile-installer: {}
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            echo "Download Amazon credentials"
+
+            staging_file_local_path=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/staging.plist
+            prod_file_local_path=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/prod.plist
+            amazon_consts_file=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/OTAmazonConsts.h
+            mixpanel_consts_file=$BITRISE_SOURCE_DIR/entourage/Settings/Environment/OTMixpanelConsts.h
+
+            # download the fileS
+            wget -O "$staging_file_local_path" "$BITRISEIO_STAGING_PLIST_URL"
+            wget -O "$prod_file_local_path" "$BITRISEIO_PRODUCTION_PLIST_URL"
+
+            wget -O "$amazon_consts_file" "$BITRISEIO_OTAMAZONCONSTS_URL"
+            wget -O "$mixpanel_consts_file" "$BITRISEIO_OTMIXPANELCONSTS_URL"
+
+            #gem install badge
+    - recursive-touch:
+        inputs:
+        - touch_time: '2017-10-25T15:00:00+00:00'
+    - fastlane:
+        inputs:
+        - lane: refresh_dsyms api_token:$CRASHLYTICS_API_TOKEN
 app:
   envs:
   - opts:
